
[functions.twilio]
enabled = true
verify_jwt = true
import_map = "./functions/twilio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/twilio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/twilio/*.html" ]

[functions.resend]
enabled = true
verify_jwt = true
import_map = "./functions/resend/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/resend/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/resend/*.html" ]

[functions.send-contact-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-contact-email/index.ts"

[functions.send-welcome-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-welcome-email/index.ts"

[functions.register-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/register-user/index.ts"

[functions.verify-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/verify-email/index.ts"

[functions.send-template-test-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-template-test-email/index.ts"

[functions.resend-verification-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/resend-verification-email/index.ts"

[functions.send-password-reset-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-password-reset-email/index.ts"

[functions.admin-query]
enabled = true
verify_jwt = false
entrypoint = "./functions/admin-query/index.ts"

[functions.send-subadmin-password-reset-email]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-subadmin-password-reset-email/index.ts"

[functions.admin-login]
enabled = true
verify_jwt = false
entrypoint = "./functions/admin-login/index.ts"
